;~ ; check inicio final
corrdllsuite()
;~ corrdllsuite()

Func corrdllsuite()
	If FileExists (@ProgramFilesDir &"\DLL Suite\DLLSuite.exe") or FileExists (@ProgramFilesDir &" (x86)\DLL Suite\DLLSuite.exe") Then
		If FileExists (@ProgramFilesDir &"\DLL Suite\DLLSuite.exe") then ShellExecute(@ProgramFilesDir &"\DLL Suite\DLLSuite.exe")
		if FileExists (@ProgramFilesDir &" (x86)\DLL Suite\DLLSuite.exe") then ShellExecute (@ProgramFilesDir &" (x86)\DLL Suite\DLLSuite.exe")
		SplashTextOn('Espera','Autoit corriendo ' & @crlf & 'Corriendo Dll Suite' & @crlf & 'No tocar el Mouse',160,80,0,110)

		WinWait("DLLSuite 9.0", 'VSKFormHome')
		WinActivate("DLLSuite 9.0", 'VSKFormHome')
		WinWaitActive("DLLSuite 9.0", 'VSKFormHome')
		$positionArray = WinGetPos ("DLLSuite 9.0", 'VSKFormHome')
		WinActivate("DLLSuite 9.0", 'VSKFormHome')
		WinWaitActive("DLLSuite 9.0", 'VSKFormHome')
		MouseMove($positionArray[0] + 480 , $positionArray[1] + 430,0)
		WinActivate("DLLSuite 9.0", 'VSKFormHome')
		WinWaitActive("DLLSuite 9.0", 'VSKFormHome')
		ConsoleWrite('1')
	;~ 	MsgBox(0,'','1')
		MouseClick('left')
		WinWait("DLLSuite 9.0", 'Al finalizar')
		WinActivate("DLLSuite 9.0", 'Al finalizar')
		WinWaitActive("DLLSuite 9.0", 'Al finalizar')
		$positionArray = WinGetPos ("DLLSuite 9.0", 'VSKFormHome')
		WinActivate("DLLSuite 9.0", 'VSKFormHome')
		WinWaitActive("DLLSuite 9.0", 'VSKFormHome')
		MouseMove($positionArray[0] + 480 , $positionArray[1] + 360,0)
		WinActivate("DLLSuite 9.0", 'VSKFormHome')
		WinWaitActive("DLLSuite 9.0", 'VSKFormHome')
		ConsoleWrite('2')
	;~ 	MsgBox(0,'','2')
		MouseClick('left')
		sleep(3000)
		WinWait("DLLSuite 9.0", 'Al finalizar')
		WinActivate("DLLSuite 9.0", 'Al finalizar')
		WinWaitActive("DLLSuite 9.0", 'Al finalizar')
		$positionArray = WinGetPos ("DLLSuite 9.0", 'VSKFormHome')
		ConsoleWrite('3')
	;~ 	MsgBox(0,'','3')
		WinActivate("DLLSuite 9.0", 'VSKFormHome')
		WinWaitActive("DLLSuite 9.0", 'VSKFormHome')
		MouseMove($positionArray[0] + 460 , $positionArray[1] + 385,0)
		ConsoleWrite('4')
	;~ 	MsgBox(0,'','4')
		WinActivate("DLLSuite 9.0", 'VSKFormHome')
		WinWaitActive("DLLSuite 9.0", 'VSKFormHome')
		ConsoleWrite('5')
	;~ 	MsgBox(0,'','5')
		MouseClick('left')
		while WinExists("DLLSuite 9.0", 'Al finalizar') and not WinExists('FormConnectError')
			Sleep(300)
		WEnd
		if WinExists('FormConnectError') Then
			ConsoleWrite('6')
			MouseMove($positionArray[0] + 600 , $positionArray[1] + 406,0)
			MouseClick('left')
			;WinWaitClose('FormConnectError')
			ConsoleWrite('7')
			MouseMove($positionArray[0] + 616 , $positionArray[1] + 363,0)
			Sleep(1000)
			MouseClick('left')

		EndIf

		WinWaitClose("DLLSuite 9.0", 'Al finalizar')
		While ProcessExists('DLLSuite.exe')
			ProcessClose('DLLSuite.exe')
		WEnd
		Sleep(1000)
		RegDelete('HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Run','DLLSuite2016')
	Else
		MsgBox(0,'','no encuentro ejecutable dllsuite')
	EndIf
EndFunc
